### ISSUE TITLE
Created readme file...The Tidyverse!

### ISSUE THREAD

**Issue by KST0NE** [KST0NE/Assignment-7#1]
Updated the readme file with a review of the tidyverse package. I am sure this is something nearly everyone in the class is familiar with and uses on their own, but it has to be the one I use the most in my day-to-day life. 

Sorry I couldn't contribute something more exciting or novel, I am excited to see what other fun packages the others use!

**I am OK with Mark posting my review to the course website but please do not use my name (i.e., make it anonymous).**

**Comment by mdscheuerell** [comment]
Thanks, Kali! This is a really nice review.
